##########################################################
##################  所有profile共有的配置  #################
##########################################################

server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML5
    cache: false
