##########################################################
##################  所有profile共有的配置  #################
##########################################################

server:
  port: 8083
####################   mongodb配置       ########################
spring:
  data:
    mongodb:
      uri: mongodb://localhost/spider
  application:
    name: spiderService
